package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "lhe_bench",
    srcs = [
        "lhe_bench.cc",
        "lhe_bench.h",
    ],
    deps = [
        "//:lhe25519",
        "@com_github_google_benchmark//:benchmark",
    ],
)
